language: bash
dist: xenial
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

before_install:
  - sudo apt-get update
  - sudo apt-get install -y shellcheck --allow-unauthenticated

script:
  - ./scripts/godownloader-shfmt.sh
  - shellcheck -V
  - make lint test
